---
- name: Install Wazuh Agent with Unique Name
  hosts: all
  become: yes
  vars:
    wazuh_manager_ip: '52.13.14.98'  # Set your Wazuh manager IP here

  tasks:
    - name: Download Wazuh agent package
      get_url:
        url: https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.8.1-1_amd64.deb
        dest: /tmp/wazuh-agent_4.8.1-1_amd64.deb

    - name: Generate unique Wazuh agent name
      set_fact:
        wazuh_agent_name: "{{ inventory_hostname }}-{{ ansible_date_time.epoch }}"

    - name: Install Wazuh agent with dynamic agent name
      command: >
        WAZUH_MANAGER='{{ wazuh_manager_ip }}'
        WAZUH_AGENT_NAME='{{ wazuh_agent_name }}'
        dpkg -i /tmp/wazuh-agent_4.8.1-1_amd64.deb

    - name: Reload systemd daemon
      command: systemctl daemon-reload

    - name: Enable Wazuh agent to start on boot
      command: systemctl enable wazuh-agent

    - name: Start Wazuh agent
      command: systemctl start wazuh-agent

